server:
    port: 8081
spring:
    thymeleaf:
        prefix: file:src/main/resources/templates/
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        #database-platform: org.hibernate.dialect.MySQLDialect
        open-in-view: false
        hibernate:
            ddl-auto: none
    datasource:
        driver-class-name: org.postgresql.Driver
        #driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:postgresql://ec2-52-2-118-38.compute-1.amazonaws.com:5432/d2mjihp450p3tl
        #url: jdbc:mysql://localhost:3306/p_ventas
        username: kdwqrntbmtyaai
        #mintic_unal
        password: e3cbf75744d0796b8d8dcfa7ca986f2a682f33e256d6f11f8efa4f7df95506d8
        #Curso2021